apiVersion: apps/v1
kind: Deployment
metadata:
  name: okk6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okk6
  template:
    metadata:
      labels:
        app: okk6
    spec:
      containers:
      - image: okteto.dev/okk6:latest
        name: okk6
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/CAFESTORE-html.zip"
        - name: Vless_UUID
          value: "8eafc3e6-c9b9-41fb-a4dd-4497f7a35801"
        - name: Vless_Path
          value: "/fglkjhgcvbnfhgjkfgj"
        - name: Vmess_UUID
          value: "8eafc3e6-c9b9-41fb-a4dd-4497f7a35801"
        - name: Vmess_Path
          value: "/qwerdffffghj56ehtd"
        - name: Share_Path
          value: "/v2link"
